// try catch
void main(){
    try{
        // do something
    }catch(Exception e){
        // do something
    }finally{
        // do something
    }
}